### ISSUE TITLE
英語

### ISSUE THREAD

**Issue by probonopd** [PG-MANA/Sweetfish#3]
残念ながら、誰もが日本語を話すことができるわけではありません。 英語をデフォルト言語にしてください。 ありがとうございました。

![image](https://user-images.githubusercontent.com/2480569/200069933-93e3bd58-2a74-4c24-b242-65cb074da822.png)

**Comment by PG-MANA** [comment]
I'm sorry for the delay in commenting.
I have been away from the development of this software for some time. 

Sweetfish has a translation for en_AU by PR #2.
So I copied it as `en_US` and `en_GB`.

I tested the translation with `LANG=en_US.UTF-8 ./sweetfish`.

I'm not familiar with the differences in English between countries, but I think you'll understand it better than Japanese.
